site_name: numpyx
theme:
    name: material
    features:
        # - navigation.tabs
        - navigation.sections

nav:
    - index.md
    - reference.md
    
extra_css:
    - stylesheets/extra.css
      
markdown_extensions:
    - toc:
        toc_depth: 4
    - pymdownx.highlight
    - pymdownx.superfences
    - admonition
    - def_list

use_directory_urls: false

repo_url: https://github.com/gesellkammer/numpyx

