name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
        
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
            python-version: '3.12'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.17.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: 'cp39-* cp310-* cp311-* cp312-*'
          CIBW_SKIP: 'pp* *686* *-musllinux_*'
          CIBW_ARCHS_MACOS: 'x86_64 arm64'

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

      - name: Upload wheels
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPIPASS }}
        run: |
            echo "TWINE_USERNAME: $TWINE_USERNAME"
            echo "TWINE_PASSWORD: $TWINE_PASSWORD"
            python -m pip install -U twine virtualenv
            twine upload --verbose --skip-existing wheelhouse/*.whl
        continue-on-error: true
